[package]
name = "orcinus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-tls = "0.11.0"
futures-util = "0.3.21"
parking_lot = "0.12.1"
ring = "0.16.20"
tokio = { version = "1.20.1", features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1.20", features = ["macros", "rt-multi-thread", "net"] }
