jobs:
  publish:
    environment: crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: "actions/checkout@v2"
      - name: Install Rust
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: stable
      - name: Setup python for tools
        uses: "actions/setup-python@4"
        with:
          python-version: '3.10'
      - name: Setup toml reader
        run: pip install toml-cli
      - id: version
        name: Read release version
        run: "::set-output name=version::$(toml get --toml-path ./Cargo.toml package.version)"
      - name: Publish to crates.io
        uses: "actions-rs/cargo@v1"
        with:
          args: "--token ${{ secrets.PUBLISH_TOKEN }}"
          command: publish
      - env:
          GITHUB_TOKEN: "${{ github.token }}"
        name: Make a release
        uses: "actions/create-release@v1"
        with:
          body: ''
          draft: 'false'
          prerelease: 'false'
          release_name: "${{ steps.version.outputs.version }}"
          tag_name: "${{ github.ref }}"
name: Publish to crates.io
on:
  push:
    branches:
      - master
