jobs:
  main:
    runs-on: ubuntu-latest
    services:
      db:
        env:
          MYSQL_ROOT_PASSWORD: root
        image: mysql:8.0
        options: "--health-cmd \"mysqladmin ping\" --health-interval 10s --health-timeout 5s --health-retries 5"
        ports:
          - "3306:3306"
    steps:
      - name: Checking out
        uses: "actions/checkout@v2"
      - name: Install Rust Toolchain
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: stable
      - name: Setup Example DB
        run: "mysql --protocol tcp -uroot -proot < ./examples/testdb.sql"
      - name: "Run Example (raw_protocols)"
        uses: "actions-rs/cargo@v1"
        with:
          args: "--example raw_protocols "
          command: run
      - name: "Run Example (run)"
        uses: "actions-rs/cargo@v1"
        with:
          args: "--example run "
          command: run
      - name: "Run Example (run_ssl)"
        uses: "actions-rs/cargo@v1"
        with:
          args: "--example run_ssl "
          command: run
      - name: "Run Example (r2d2)"
        uses: "actions-rs/cargo@v1"
        with:
          args: "--example r2d2 --features r2d2-integration"
          command: run
      - name: "Run Example (r2d2_autossl)"
        uses: "actions-rs/cargo@v1"
        with:
          args: "--example r2d2_autossl --features r2d2-integration,autossl"
          command: run
      - name: "Run Example (bb8_autossl)"
        uses: "actions-rs/cargo@v1"
        with:
          args: "--example bb8_autossl --features bb8-integration,autossl"
          command: run
name: Example Test
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - dev
