jobs:
  main:
    runs-on: ubuntu-latest
    services:
      db:
        env:
          MYSQL_ROOT_PASSWORD: root
        image: mysql:8.0
        options: "--health-cmd \"mysqladmin ping\" --health-interval 10s --health-timeout 5s --health-retries 5"
        ports:
          - "3306:3306"
    steps:
      - name: Checking out
        uses: "actions/checkout@v2"
      - name: Install Rust
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: stable
      - name: Setup Example DB
        run: "mysql --protocol tcp -uroot -proot < ./examples/testdb.sql"
      - name: "Run Example(raw_protocols)"
        run: cargo run --example raw_protocols 
      - name: "Run Example(run)"
        run: cargo run --example run 
      - name: "Run Example(run_ssl)"
        run: cargo run --example run_ssl 
      - name: "Run Example(r2d2)"
        run: cargo run --example r2d2 --features r2d2-integration
      - name: "Run Example(r2d2_autossl)"
        run: "cargo run --example r2d2_autossl --features r2d2-integration,autossl"
      - name: "Run Example(bb8_autossl)"
        run: "cargo run --example bb8_autossl --features bb8-integration,autossl"
name: Example Test
on:
  pull_request:
    types:
      - opened
      - synchronize
